# a mybinder.org-ready environment for demoing jvox_jlab_ext
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jvox-jlab-ext-demo
#
name: jvox-jlab-ext-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.14,<3.15
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=22,<23
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
