[project]
name = "jvox_server_commons"
version = "0.1.0"
description = "Common configuration and utilities for the JVox server components."
authors = [
    { name="WWang" }
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
