[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jvox_ai_magics"
version = "0.1.0"
description = "Custom AI-related magics from JupyterVox"
dependencies = [
    "ipython>=7.0.0",
]